### ISSUE TITLE
cannot load such file -- pry (LoadError)

### ISSUE THREAD

**Issue by rye** [frc-frecon/frecon#94]
The FReCon Console cannot load "pry" because it is not included properly in the bundle.  For some reason this issue hasn't shown up in CI, (probably because the console itself is not tested yet) but it's now showing up in the BBB in our deploy.  Here's a screenshot for proof.

![slack for ios upload](https://cloud.githubusercontent.com/assets/1566689/13792509/26a27278-eac0-11e5-995f-08a07414a93c.jpg)

Easy fix.  Add it to the bundle.

**Comment by Sammidysam** [comment]
I actually remember running into this problem a long time ago.  But really I don't remember what I did about it.  Maybe I installed `pry` and then it worked again?  Either way, it's not of any concern.

**Comment by rye** [comment]
By adding it as a gem dependency, we prevent this issue.  This problem is from our old days of upgrading from IRB to Pry&mdash;as I recall, we would try and require Pry, and, upon error, revert back to IRB&mdash;I just didn't explicitly add it as a dependency.  I figure that we all want to use Pry, and, since we have other dependencies in this project, it's perfectly acceptable to fold Pry in with them.

**Comment by Sammidysam** [comment]
Yes, I agree.

-Sam

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.6.30&pv=6.0&source=email_footer_2] On Sun, Jul 31, 2016 at 2:24 PM, Kristofer Rye < notifications@github.com [notifications@github.com] > wrote:
By adding it as a gem dependency, we prevent this issue. This problem is from our old days of upgrading from IRB to Pry—as I recall, we would try and require Pry, and, upon error, revert back to IRB—I just didn't explicitly add it as a dependency. I figure that we all want to use Pry, and, since we have other dependencies in this project, it's perfectly acceptable to fold Pry in with them.
